FROM tomcat:7-jre8

MAINTAINER Hugo Gonzalez <hgonzalez@railtronix.com>

ADD tomcat-users.xml /usr/local/tomcat/config/ 
ADD server.xml /usr/local/tomcat/config/
ADD webapps/BaillysTransportServices.war /usr/local/tomcat/webapps/

